### ISSUE TITLE
[Scripts/create_plugin.py] can't build plugin (somehow related to Markdown)

### ISSUE THREAD

**Issue by janzandr** [EnMAP-Box/enmap-box#452]
Running the script gives error: 
```
C:\QGIS\bin\python.exe D:/source/QGISPlugIns/enmap-box/scripts/create_plugin.py 
Traceback (most recent call last):
  File "D:\source\QGISPlugIns\enmap-box\scripts\create_plugin.py", line 34, in <module>
    import markdown
  File "C:\QGIS\apps\Python39\lib\site-packages\markdown\__init__.py", line 29, in <module>
    from .core import Markdown, markdown, markdownFromFile  # noqa: E402
  File "C:\QGIS\apps\Python39\lib\site-packages\markdown\core.py", line 26, in <module>
    from . import util
  File "C:\QGIS\apps\Python39\lib\site-packages\markdown\util.py", line 88, in <module>
    INSTALLED_EXTENSIONS = metadata.entry_points(group='markdown.extensions')
TypeError: entry_points() got an unexpected keyword argument 'group'
```

**Comment by jakimowb** [comment]
which markdown & python version do you use?

**Comment by janzandr** [comment]
Markdown-3.3.7, after updating to 3.4.3 it works.
